i2c:
  sda: GPIO7
  scl: GPIO8
  scan: true
  frequency: 400kHz
  id: bus_a

display:
  - platform: mipi_dsi
    id: main_display
    model: JC1060P470
    update_interval: 1s
    auto_clear_enabled: true
    reset_pin:
      number: GPIO05
    hsync_pulse_width: 20
    rotation: ${rotate_display}
    lambda: |-
      it.strftime(12, 12, id(ha_time).now(), "%Y-%m-%d %H:%M:%S");
      it.printf(12, 36, "WiFi RSSI: %.1f dBm", id(panel_wifi_rssi).state);

touchscreen:
  - platform: gt911
    id: main_touch
    display: main_display
    i2c_id: bus_a
    interrupt_pin: GPIO21
    reset_pin: GPIO22
    on_touch:
      then:
        - binary_sensor.template.publish:
            id: panel_touch_input
            state: ON
    on_release:
      then:
        - binary_sensor.template.publish:
            id: panel_touch_input
            state: OFF

binary_sensor:
  - platform: template
    name: "Panel Touch Input"
    id: panel_touch_input

output:
  - platform: ledc
    id: backlight_output
    pin: GPIO23
    frequency: 100Hz
    min_power: 0.0
    max_power: 0.8

light:
  - platform: monochromatic
    id: panel_backlight
    name: "Panel Backlight"
    icon: mdi:television
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms
